module.exports = {
    // 🤖 专家角色 (Agents)
    "frontend-specialist": "擅长 React/Vue 前端开发与架构设计",
    "backend-specialist": "精通 Node/Python 后端服务与数据库",
    "mobile-developer": "iOS/Android/Flutter 移动端开发专家",
    "game-developer": "Unity/Unreal 游戏开发与图形学",
    "project-planner": "项目规划与任务拆解专家",
    "database-architect": "数据库模型设计与性能优化",
    "devops-engineer": "CI/CD、Docker 与服务器运维",
    "orchestrator": "多智能体任务协调与分发",
    "security-auditor": "代码安全审计与漏洞分析",
    "penetration-tester": "模拟攻击与渗透测试",
    "test-engineer": "自动化测试与 QA 流程",
    "debugger": "复杂 Bug 诊断与修复专家",
    "performance-optimizer": "应用性能分析与优化",
    "seo-specialist": "搜索引擎优化与关键词策略",
    "documentation-writer": "高质量技术文档与 API 文档撰写",
    "explorer-agent": "新技术调研与可行性分析",

    // 🧠 专业技能 (Skills)
    "frontend-design": "前端 UI 组件与交互设计模式",
    "ui-ux-pro-max": "高级 UI/UX 设计原则与实现",
    "react-patterns": "React 最佳实践与设计模式",
    "nextjs-best-practices": "Next.js SSR/SSG 全栈开发指南",
    "tailwind-patterns": "Tailwind CSS 原子化样式技巧",
    "mobile-design": "移动端响应式与交互设计",
    "api-patterns": "REST/GraphQL API 设计规范",
    "nestjs-expert": "NestJS 架构与企业级应用",
    "nodejs-best-practices": "Node.js 性能与代码规范",
    "python-patterns": "Python 编程范式与技巧",
    "database-design": "ER 建模与 SQL/NoSQL 选型",
    "prisma-expert": "Prisma ORM 高级用法",
    "app-builder": "应用脚手架与快速构建",
    "architecture": "系统架构设计模式 (DDD/Clean)",
    "mcp-builder": "MCP 协议与工具链开发",
    "typescript-expert": "TypeScript 高级类型与配置",
    "docker-expert": "Docker 容器化与编排",
    "deployment-procedures": "生产环境部署标准流程",
    "server-management": "Linux 服务器管理与监控",
    "bash-linux": "Shell 脚本与 Linux 命令大全",
    "powershell-windows": "PowerShell 自动化脚本",
    "testing-patterns": "单元/集成/E2E 测试策略",
    "webapp-testing": "Web 应用专项测试技术",
    "tdd-workflow": "测试驱动开发 (TDD) 实战",
    "code-review-checklist": "代码审查 check list 规范",
    "lint-and-validate": "代码风格检查与格式化配置",
    "clean-code": "Clean Code 代码整洁之道",
    "systematic-debugging": "系统化调试方法论",
    "performance-profiling": "性能瓶颈剖析与调优",
    "vulnerability-scanner": "常见安全漏洞扫描与修复",
    "red-team-tactics": "红队攻击视角与防御",
    "seo-fundamentals": "SEO 核心原理与实施",
    "geo-fundamentals": "地理信息系统基础",
    "i18n-localization": "国际化与多语言适配方案",
    "plan-writing": "编写清晰可执行的技术方案",
    "brainstorming": "创意风暴与思维发散",
    "behavioral-modes": "定义 Agent 的行为与语气模式",
    "parallel-agents": "并发多 Agent 协作模式",
    "documentation-templates": "各类技术文档Markdown模板",

    // ⚡ 快捷指令 (Workflows)
    "/menu": "打开主菜单 (Alt+X)",
    "/create": "创建新项目或文件",
    "/debug": "启动系统化调试流程",
    "/plan": "制定实施计划 (Task & Checklists)",
    "/ui-ux-pro-max": "进入高级 UI/UX 设计模式",
    "/brainstorm": "开始头脑风暴会议",
    "/deploy": "部署应用到生产/预发环境",
    "/enhance": "优化现有代码质量",
    "/orchestrate": "协调多个 Agent 共同完成任务",
    "/preview": "预览当前组件或页面",
    "/status": "查看当前任务状态",
    "/test": "运行测试套件"
};
